#Terraform deployment

trigger:
- main

pool:
  name: Default

jobs:
- job: 'checkout_code'
  steps:
  - checkout: self

- job: 'deploy_terraform'
  steps:
  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    displayName: 'Terraform init'
    inputs:
      command: init
      provider: azurerm
      backendServiceArm: 'sc-devops-vaneck-001'
      backendAzureRmResourceGroupName: 'rg-devops-weu-001'
      backendAzureRmStorageAccountName: 'stgvaneckdevops001'
      backendAzureRmContainerName: 'terraformstate'
      backendAzureRmKey: 'testing.tfstate'
